blog/urls.py
from django.urls import path
from .views import post_detail, post_list, PostListView, post_share, post_search
from .feeds import LatestPostFeed

# Пространство имен приложения
app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    # path('', PostListView.as_view(), name="post_list"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path('<int:post_id>/share/', post_share, name="post_share"),
    path('feed/', LatestPostFeed(), name='post_feed'),
    path('search/', post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'posts': PostSitemap,}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

# Создаём свой менеджер моделей. Указывается до самих моделей, его использующих


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='Автор')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now, verbose_name='Дата публикации')
    print(publish)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Отредактировано')
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='Статус')
    # указываем менеджеры объектов, если добавили свой
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail",
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug]
                       )
    # Возвращает правильную форму для множественного числа.
    def get_plural(self):
        comments = len(self.comments.filter(active=True))
        if 0 <= comments <= 1000:
            x = comments % 10
            y = comments % 100
            if y == 11:
                return 'комментариев'
            elif x == 1 and y != 11:
                return 'комментарий'
            if  y in [12, 13, 14]:
                return 'комментариев'
            elif x in [2, 3, 4] and y not in [12, 13, 14]:
                return 'комментария'
            if x in [0, 5, 6, 7, 8, 9]:
                return 'комментариев'

class Comment(models.Model):
    # related_name позволяет обращаться к комментариям из связанной модели вот так: Post.comments.all()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, verbose_name='Имя')
    email = models.EmailField()
    body = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Отредактировано')
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'Комментарий от {self.name} к записи {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label="Имя")
    email = forms.EmailField()
    to = forms.EmailField(label="Кому")
    comments = forms.CharField(required=False, widget=forms.Textarea, label="Комментарии")

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(label='Запрос')

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
# Create your views here.


class PostListView(ListView):
    # Если бы мы указали model = Post, то использовался бы стандартный менеджер модели.
    queryset = Post.published.all()
    # задаем переменную контекста HTML-шаблона. По умолчанию: object_list
    context_object_name = 'posts'
    # Пагинатор по 3 поста на странице
    paginate_by = 3
    # По умолчанию blog/post_list.html
    template_name = "blog/post/list.html"


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    # По 3 статьи на каждой странице
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем их общее количество - возвращаем последнюю.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month, publish__day=day)
    # Список активных комментариев для статьи
    comments = post.comments.filter(active=True)
    new_comment = None
    # Возвращает правильную форму для множественного числа.
    ruplural = post.get_plural()
    if request.method == 'POST':
        # Пользователь отправил комментарий
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к статье
            new_comment.post = post
            # Сохраняем комментарий в БД
            new_comment.save()
    else:
        comment_form = CommentForm()
    # Формирование списка похожих статей
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'ruplural': ruplural,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    # Получение статьи по идентификатору
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Форма отправляется на сохранение
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # Отправка почты
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) рекомендует Вам прочесть "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Прочтите "{}" тут {}\n\n комментарий от пользователя {}: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'dancing-star@inbox.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector(
                'title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.2).order_by('-rank')

            if not results:
                print(results)
                results = Post.objects.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
                print(results)

    return render(request, 'blog/post/search.html', {
        'form': form,
        'query': query,
        'results': results
    })

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock title %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">Опубликовано {{ post.publish }}, автор {{ post.author }}</p>
{{ post.body|markdown }}
<p><a href="{% url 'blog:post_share' post.id %}">Поделиться этой статьей</a></p>

<h2>Похожие посты:</h2>

{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
<p>Похожих постов пока нет.</p>
{% endfor %}

{% with comments.count as total_comments %}
<!-- Я реализовал свою функцию для множественного числа -->
<h2>{{ total_comments }} {{ ruplural }}</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment">
    <p class="info">Комментарий № {{ forloop.counter }} от {{ comment.created }}, автор: {{ comment.name}}</p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>Комментариев пока нет</p>
{% endfor %}

{% if new_comment %}
<h2>Ваш комментарий был добавлен.</h2>
{% else %}
<h2>Добавить новый комментарий</h2>
<form action="." method="POST">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Добавить комментарий"></p>
</form>
{% endif %}
{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}Мой блог{% endblock title %}

{% block content %}
<h1>Мой Блог</h1>

{% if tag %}
<h2>Посты связанные с "{{ tag.name }}"</h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</h2>
<p class="tags">
    Метки:
    {% for tag in post.tags.all %}
    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
<p class="date">Опубликовано {{ post.publish }}, автор {{ post.author }}</p>
<!-- обрезает статьи, после указанного количества. linebreaks преобразует в HTML с переносами строки. -->
{{ post.body|markdown|truncatewords_html:30 }}
{% endfor %}
<!-- page_obj используется по умолчанию в PostListView. posts в нашей функции -->
{% include "pagination.html" with page=posts %}
{% endblock content %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}Поиск{% endblock title %}


{% block content %}

{% if query %}
<h1>Посты содержащие "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Количество найденных статей: {{ total_results }}
    {% endwith %}
</h3>

{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
{{ post.body|truncatewords:5 }} <br><br>
{% empty %}
<p>По вашему запросу результатов не найдено!</p>
{% endfor %}
<p><a href=" {% url 'blog:post_search' %}">Искать снова</a></p>
{% else %}
<h1>Поиск по постам</h1>
<form action="." method="GET">
    {{ form.as_p }}
    <input type="submit" value="Искать">
</form>
{% endif %}

{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Поделиться статьей{% endblock title %}

{% block content %}
    {% if sent %}
        <h1>Письмо успешно отправлено!</h1>
        <p>Статья "{{ post.title }}", успешно отправлена на e-mail {{ form.cleaned_data.to }}.</p>
    {% else %}
    <h1>Отправить "{{ post.title }}" по e-mail</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Отправить e-mail">
    </form>
    {% endif %}
{% endblock content %}